// TypesFromSerializers CacheKey 8f0921f7b52ce6c7e00678addb35edfd
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Enrollment {
  id: number
  active: boolean
  courseName: string
  durationMinutes: number
  frequencyPerWeek: number
  meetLink: string
  paymentStatus: string
  salesId: number
  startDate: string | Date
  student: unknown
  teacherId: number
  totalSessions: number
  tuitionNote?: string
}
