// TypesFromSerializers CacheKey a91d828304c5aea5304b4aef9a40e4e5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Item {
  id: number
  createdAt: string | Date
  description?: string
  name: string
  phoneNumber?: string
  updatedAt: string | Date
}
