// TypesFromSerializers CacheKey 1db8b35837735d291a588ac3e6ed07bf
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface LessonSession {
  id: number
  csForm: string
  csStatus: string
  dayLabel: string
  durationMinutes: number
  endTime: string | Date
  enrollment: unknown
  lessonNotes?: string
  lessonStatus: string
  scheduledOn: string | Date
  startTime: string | Date
  teacherId: number
  teacherName: unknown
}
