// TypesFromSerializers CacheKey 8b28c64b7db18c80f0362223871369ee
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Person {
  id: number
  active: boolean
  name: string
  role: 'teacher' | 'sales' | 'cs'
  weeklyAvailabilityTarget?: number
}
