// TypesFromSerializers CacheKey 228f68e471c959319fb07c1f3ac4628b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Student {
  id: number
  aim?: string
  baseline?: string
  code: string
  examDate?: string | Date
  name: string
  studentNote?: string
}
