// TypesFromSerializers CacheKey b802cb124b41b187d10bc21303d08cf5
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface TeacherAvailability {
  id: number
  availableOn: string | Date
  durationMinutes: number
  endTime: string | Date
  startTime: string | Date
  teacherId: number
}
