// TypesFromSerializers CacheKey 584a9b36e7ef59c9fe0cdb73d37034c2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface User {
  id: number
  avatarUrl?: string
  email: string
  name?: string
}
