// TypesFromSerializers CacheKey 88f7dd38d68610f8e7ffe6f12af6b29d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.

export default interface Version {
  id: number
  createdAt: string
  event: string
  itemId: number
  itemType: string
  object: Record<string, unknown> | null
  objectChanges: Record<string, [unknown, unknown]> | null
}
